// <auto-generated />
using System;
using KaizokuBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaizokuBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("KaizokuBackend.Models.Database.EnqueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnqueuedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraKey")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("JobParameters")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("FinishedDate")
                        .HasDatabaseName("IX_Enqueue_FinishedDate");

                    b.HasIndex("GroupKey")
                        .HasDatabaseName("IX_Enqueue_GroupKey");

                    b.HasIndex("Key");

                    b.HasIndex("Queue");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.HasIndex("JobType", "ExtraKey")
                        .HasDatabaseName("IX_Enqueue_JobType_ExtraKey");

                    b.HasIndex("JobType", "Status")
                        .HasDatabaseName("IX_Enqueue_JobType_Status");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.EtagCacheEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("ExternalEtag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("MihonProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextUpdateUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("Key");

                    b.HasIndex("NextUpdateUTC");

                    b.HasIndex("Url");

                    b.ToTable("ETagCache");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.HealthStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AffectedSeriesJson")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "affectedSeriesJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "resolvedAt");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "targetId");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "targetType");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_HealthStatus_IsActive");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_HealthStatus_Level");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_HealthStatus_Target");

                    b.ToTable("HealthStatuses");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.ImportEntity", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("ContinueAfterChapter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("Path");

                    b.HasIndex("Status", "Action")
                        .HasDatabaseName("IX_Import_Status_Action");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobParameters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("MinutePlace")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextExecution")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreviousExecution")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<TimeSpan>("TimeBetweenJobs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_Job_IsEnabled");

                    b.HasIndex("Key");

                    b.HasIndex("NextExecution");

                    b.HasIndex("JobType", "GroupKey")
                        .HasDatabaseName("IX_Job_JobType_GroupKey");

                    b.HasIndex("JobType", "Key")
                        .HasDatabaseName("IX_Job_JobType_Key");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.LatestSerieEntity", b =>
                {
                    b.Property<string>("MihonId")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("BridgeItemInfo")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<long?>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime>("FetchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InLibrary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<decimal?>("LatestChapter")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestChapterTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("MihonProviderId")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("MihonId");

                    b.HasIndex("FetchDate")
                        .HasDatabaseName("IX_LatestSerie_FetchDate");

                    b.HasIndex("MihonProviderId")
                        .HasDatabaseName("IX_LatestSerie_MihonProviderId");

                    b.HasIndex("Provider")
                        .HasDatabaseName("IX_LatestSerie_Provider");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_LatestSerie_Title");

                    b.ToTable("LatestSeries");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.ProviderStorageEntity", b =>
                {
                    b.Property<string>("MihonProviderId")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<bool>("IsBroken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNSFW")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStorage")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "isStorage");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "provider");

                    b.Property<string>("Scanlator")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "scanlator");

                    b.Property<string>("SourcePackageName")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("SourceRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRepositoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<bool>("SupportLatest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnailUrl");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("MihonProviderId");

                    b.HasIndex("Name");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.SeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "artist");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "author");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "chapterCount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "genre");

                    b.Property<DateTime?>("LastChapterDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lastChapterDate");

                    b.Property<bool>("PauseDownloads")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "pauseDownloads");

                    b.Property<decimal?>("StartFromChapter")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "startFromChapter");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("StoragePath")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "storagePath");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.SeriesProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("BridgeItemInfo")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<long?>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("ContinueAfterChapter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime?>("FetchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCover")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNSFW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStorage")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "isStorage");

                    b.Property<bool>("IsTitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUninstalled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnknown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "language");

                    b.Property<DateTime?>("LastErrorDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastKnownStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeriesInfoRefreshDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulFetchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MihonId")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("MihonProviderId")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "provider");

                    b.Property<string>("Scanlator")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "scanlator");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("MihonId")
                        .HasDatabaseName("IX_SeriesProvider_MihonId");

                    b.HasIndex("MihonProviderId")
                        .HasDatabaseName("IX_SeriesProvider_MihonProviderId");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("IX_SeriesProvider_SeriesId");

                    b.HasIndex("Title", "Language")
                        .HasDatabaseName("IX_SeriesProvider_Title_Language");

                    b.HasIndex("Provider", "Language", "Scanlator")
                        .HasDatabaseName("IX_SeriesProvider_Provider_Language_Scanlator");

                    b.ToTable("SeriesProviders");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.SettingEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("Name");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.SeriesProviderEntity", b =>
                {
                    b.HasOne("KaizokuBackend.Models.Database.SeriesEntity", null)
                        .WithMany("Sources")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaizokuBackend.Models.Database.SeriesEntity", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
