// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RensaioBackend.Data;

#nullable disable

namespace RensaioBackend.Migrations.Rensaio.Postgres
{
    [DbContext(typeof(PostgresAppDbContext))]
    [Migration("20260922171045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RensaioBackend.Models.Database.EnqueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnqueuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobParameters")
                        .HasColumnType("text");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("FinishedDate")
                        .HasDatabaseName("IX_Enqueue_FinishedDate");

                    b.HasIndex("GroupKey")
                        .HasDatabaseName("IX_Enqueue_GroupKey");

                    b.HasIndex("Key");

                    b.HasIndex("Queue");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.HasIndex("JobType", "ExtraKey")
                        .HasDatabaseName("IX_Enqueue_JobType_ExtraKey");

                    b.HasIndex("JobType", "Status")
                        .HasDatabaseName("IX_Enqueue_JobType_Status");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.EtagCacheEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalEtag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MihonProviderId")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextUpdateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("NextUpdateUTC");

                    b.HasIndex("Url");

                    b.ToTable("ETagCache");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.HealthStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AffectedSeriesJson")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "affectedSeriesJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "resolvedAt");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "targetId");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "targetType");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_HealthStatus_IsActive");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_HealthStatus_Level");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_HealthStatus_Target");

                    b.ToTable("HealthStatuses");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.ImportEntity", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<int>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("ContinueAfterChapter")
                        .HasColumnType("numeric");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Path");

                    b.HasIndex("Status", "Action")
                        .HasDatabaseName("IX_Import_Status_Action");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("JobParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinutePlace")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PreviousExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<TimeSpan>("TimeBetweenJobs")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_Job_IsEnabled");

                    b.HasIndex("Key");

                    b.HasIndex("NextExecution");

                    b.HasIndex("JobType", "GroupKey")
                        .HasDatabaseName("IX_Job_JobType_GroupKey");

                    b.HasIndex("JobType", "Key")
                        .HasDatabaseName("IX_Job_JobType_Key");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.LatestSerieEntity", b =>
                {
                    b.Property<string>("MihonId")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("BridgeItemInfo")
                        .HasColumnType("text");

                    b.Property<long?>("ChapterCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InLibrary")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("LatestChapter")
                        .HasColumnType("numeric");

                    b.Property<string>("LatestChapterTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MihonProviderId")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("MihonId");

                    b.HasIndex("FetchDate")
                        .HasDatabaseName("IX_LatestSerie_FetchDate");

                    b.HasIndex("MihonProviderId")
                        .HasDatabaseName("IX_LatestSerie_MihonProviderId");

                    b.HasIndex("Provider")
                        .HasDatabaseName("IX_LatestSerie_Provider");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_LatestSerie_Title");

                    b.ToTable("LatestSeries");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.ProviderStorageEntity", b =>
                {
                    b.Property<string>("MihonProviderId")
                        .HasColumnType("text");

                    b.Property<bool>("IsBroken")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNSFW")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStorage")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isStorage");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "provider");

                    b.Property<string>("Scanlator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "scanlator");

                    b.Property<string>("SourcePackageName")
                        .HasColumnType("text");

                    b.Property<string>("SourceRepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("SourceRepositoryName")
                        .HasColumnType("text");

                    b.Property<string>("SourceSourceId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<bool>("SupportLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnailUrl");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("MihonProviderId");

                    b.HasIndex("Name");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.SeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "artist");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "author");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "chapterCount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "genre");

                    b.Property<DateTime?>("LastChapterDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "lastChapterDate");

                    b.Property<bool>("PauseDownloads")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "pauseDownloads");

                    b.Property<int?>("ReleaseCadenceDays")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "releaseCadenceDays");

                    b.Property<decimal?>("StartFromChapter")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "startFromChapter");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "storagePath");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.SeriesMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativeTitles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalSeriesId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalSeriesTitle")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LinkedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedSitesIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MappingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("MetaData")
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("SeriesCoverUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserUid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalSeriesId")
                        .HasDatabaseName("IX_SeriesMapping_Provider_ExternalSeriesId");

                    b.HasIndex("SeriesId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("IX_SeriesMapping_SeriesId_Provider");

                    b.ToTable("SeriesMappings");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.SeriesProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("BridgeItemInfo")
                        .HasColumnType("text");

                    b.Property<long?>("ChapterCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("ContinueAfterChapter")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FetchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNSFW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStorage")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isStorage");

                    b.Property<bool>("IsTitle")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUninstalled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnknown")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "language");

                    b.Property<DateTime?>("LastErrorDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastKnownStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSeriesInfoRefreshDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessfulFetchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MihonId")
                        .HasColumnType("text");

                    b.Property<string>("MihonProviderId")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "provider");

                    b.Property<string>("Scanlator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "scanlator");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("MihonId")
                        .HasDatabaseName("IX_SeriesProvider_MihonId");

                    b.HasIndex("MihonProviderId")
                        .HasDatabaseName("IX_SeriesProvider_MihonProviderId");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("IX_SeriesProvider_SeriesId");

                    b.HasIndex("Title", "Language")
                        .HasDatabaseName("IX_SeriesProvider_Title_Language");

                    b.HasIndex("Provider", "Language", "Scanlator")
                        .HasDatabaseName("IX_SeriesProvider_Provider_Language_Scanlator");

                    b.ToTable("SeriesProviders");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.SettingEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AvatarBlob")
                        .HasColumnType("bytea");

                    b.Property<string>("AvatarContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OpdsPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OpdsPath")
                        .IsUnique()
                        .HasDatabaseName("IX_User_OpdsPath");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.UserExternalLoginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserExternalLogin_UserId");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("IX_UserExternalLogin_Issuer_Subject");

                    b.ToTable("UserExternalLogins");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.UserScrobblerConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<bool>("AutoSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastDownloadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUploadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("IX_UserScrobblerConfig_UserId_Provider");

                    b.ToTable("UserScrobblerConfigs");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.SeriesMappingEntity", b =>
                {
                    b.HasOne("RensaioBackend.Models.Database.SeriesEntity", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.SeriesProviderEntity", b =>
                {
                    b.HasOne("RensaioBackend.Models.Database.SeriesEntity", null)
                        .WithMany("Sources")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.UserExternalLoginEntity", b =>
                {
                    b.HasOne("RensaioBackend.Models.Database.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.UserScrobblerConfigEntity", b =>
                {
                    b.HasOne("RensaioBackend.Models.Database.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RensaioBackend.Models.Database.SeriesEntity", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
